development:
  adapter: postgresql
  database: twitter_searcher_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: twitter_searcher_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: twitter_searcher_production
  pool: 5
  timeout: 5000
